[package]
name = "atlas_holdem"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
atlas-core = { workspace = true }
atlas-scheme = { workspace = true }

# runtime
tokio = { workspace = true, features = ["full"] }

# common
ulid = { workspace = true, features = ["serde"] }
#sha2 = "0.10.9"
#hex = "0.4.3"
rand = "0.9"
rs_poker = { version = "4.1.0",default-features = false ,features = ["serde"] }